return {
    name = "basic",
    short = _("Basic"),
    locked = true,
    profile_name = _("Basic - see enemy SAM mid/long range"),
    show_humans = 1,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 2,
    ground_radar = 0,
    automatic_info_friend = 0,
    automatic_info_neutral = 0,
    automatic_info_eni = 1,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = true,
    use_callsign = 1,
    use_rcs = false,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 0,
    use_range_resolution = false,
    use_datalink = true,
    datalink_info_mode = 1,
    use_taf = true,
}
