return {
    name = "WWII",
    short = _("WWII"),
    profile_name = _("WWII"),
    locked = true,
    show_weapons = false,
    relief_filter = true,
    speed_filter = true,
    radar = 3,
    ground_radar = 3,
    use_rcs = true,
    use_scan_period = false,
    automatic_info_friend = 2,
    automatic_info_neutral = 2,
    automatic_info_eni = 2,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = true,
    use_callsign = 2,
    modelisation = "network",
    tracking_delay = 20,
    use_realtracking = true,
    use_range_resolution = true,
    use_datalink = false,
    datalink_period = 5,
}
