lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.3.11.401
    -- Date    :27.05.2024 04:22:37
    virtual_awacs_name = "",
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    dedicated_profile = "cav_realism.lua",
    use_admin_commands = false,
    dump_json_stats = false,
    export_log = false,
    export_tacview = false,
    perfs_tests = false,
}
