lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.3.11.401
    -- Date    :27.05.2024 04:22:37
    virtual_awacs_name = "",
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    dedicated_profile = "cav_realism.lua",
    use_admin_commands = false,
    dump_json_stats = false,
    export_log = false,
    export_tacview = false,
    perfs_tests = false,
    red_password = "red",
    blue_password = "blue",
    chat_connect_message = "coalition",
    port = 10320,
    use_jsonserver = true,
    jsonserver_port = 8070,
    srs_use_transponder = true,
    srs_transponder_port = 10710,
}
