cfg = 
{
    ["current"] = 1,
    ["description"] = "Join our Discord at https://discord.gg/7cav",
    ["require_f_textures"] = false,
    ["require_pure_textures"] = false,
    ["listStartIndex"] = 2,
    ["advanced"] = 
    {
        ["allow_change_tailno"] = true,
        ["disable_events"] = false,
        ["allow_ownship_export"] = true,
        ["allow_object_export"] = true,
        ["pause_on_load"] = true,
        ["allow_sensor_export"] = true,
        ["event_Takeoff"] = true,
        ["pause_without_clients"] = false,
        ["client_outbound_limit"] = 0,
        ["client_inbound_limit"] = 0,
        ["server_can_screenshot"] = true,
        ["allow_players_pool"] = false,
        ["voice_chat_server"] = false,
        ["allow_change_skin"] = true,
        ["event_Connect"] = true,
        ["event_Ejecting"] = true,
        ["event_Kill"] = false,
        ["event_Crash"] = true,
        ["event_Role"] = false,
        ["resume_mode"] = 1,
        ["maxPing"] = 0,
        ["allow_trial_only_clients"] = true,
        ["allow_dynamic_radio"] = false,
    }, -- end of ["advanced"]
    ["port"] = 10311,
    ["mode"] = 0,
    ["bind_address"] = "",
    ["isPublic"] = true,
    ["missionList"] = {}, -- end of ["missionList"]
    ["password"] = "",
    ["listShuffle"] = false,
    ["name"] = "Template Server",
    ["require_pure_scripts"] = false,
    ["listLoop"] = false,
    ["require_pure_clients"] = false,
    ["require_pure_models"] = false,
    ["maxPlayers"] = 64,
} -- end of cfg
