return {
    name = "arcade",
    short = _("Arcade"),
    profile_name = _("Arcade - see all"),
    locked = true,
    show_humans = 0,
    show_weapons = true,
    speed_filter = false,
    relief_filter = false,
    radar = 0,
    ground_radar = 0,
    automatic_info_friend = 0,
    automatic_info_neutral = 0,
    automatic_info_eni = 0,
    approach_all_airports = 2,
    airport_radar_mode = 1,
    force_player_name = true,
    use_callsign = 1,
    use_rcs = false,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 0,
    use_range_resolution = false,
    use_datalink = true,
    datalink_info_mode = 0,
    use_taf = true,
}
