return {
    name = "cav_realism",
    short = _("Cav Realism"),
    locked = false,
    profile_name = _("Enhanced Realism Profile"),
    show_humans = 1,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 3,
    ground_radar = 4,   
    automatic_info_friend = 0,
    automatic_info_neutral = 0,
    automatic_info_eni = 0,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = false,
    use_callsign = 2,
    use_rcs = true,    
    use_realtracking = true,
    modelisation = "global",
    tracking_delay = 6,
    use_range_resolution = true,
    use_datalink = true,
    datalink_info_mode = 2,
    use_taf = true,
}

