return {
    name = "realistic",
    short = _("Realistic"),
    locked = true,
    profile_name = _("Realistic - see only what you can really see"),
    show_humans = 2,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 3,
    ground_radar = 4,
    automatic_info_friend = 0,
    automatic_info_neutral = 1,
    automatic_info_eni = 2,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = false,
    use_callsign = 0,
    use_rcs = true,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 6,
    use_range_resolution = true,
    use_datalink = true,
    datalink_info_mode = 2,
    use_taf = true,
}
